Feature/admin panel
igor-arkhipov/TaskManager pull request #11
Opened 2021-12-06 07:31 UTC by igor-arkhipov

2021-12-07 07:04 UTC, greybutton requested changes

2021-12-07 07:04 UTC, greybutton commented on test/controllers/web/boards_controller_test.rb
> +  end
сетап выше всех тестов обычно, а не ниже

2021-12-07 07:04 UTC, greybutton commented on test/factories/users.rb
> -
почему удалил?

2021-12-08 00:03 UTC, igor-arkhipov commented on test/factories/users.rb
> -
Тест ругается на дубль
`Factory already registered: admin (FactoryBot::DuplicateDefinitionError)`

Более усложнённую фабрику сделать надо было же тут [test/factories/admins.rb ](test/factories/admins.rb)

2021-12-08 16:31 UTC, greybutton approved these changes

2021-12-08 17:22 UTC, merged