Complete Feature/tasks stage
igor-arkhipov/TaskManager pull request #15
Opened 2022-11-19 04:03 UTC by igor-arkhipov

2022-11-20 08:23 UTC, greybutton requested changes

2022-11-20 08:23 UTC, greybutton commented on app/controllers/api/v1/tasks_controller.rb
> +      order(id: :desc).
сортировка не хардкодится в контроллере, либо передается через рансак, либо берется дефолт

2022-11-20 08:23 UTC, greybutton commented on app/javascript/components/AddPopup/AddPopup.js
> +        console.log(`Creation Failed! Error: ${error.message}`);
почему console.log? смысл в алерты был в том, что это самый простой способ показать юзеру что не получилось

2022-11-20 08:23 UTC, greybutton commented on app/javascript/components/EditPopup/EditPopup.js
> +import useStyles from './useStyles';
сначала идут импорты внешних пакетов, потом локальные файлы

2022-11-20 08:23 UTC, greybutton commented on app/javascript/utils/fetchHelper.js
> +  async put(url, json) {
1 здесь в async смысла нет, вызов функции и внутри все равно с промисом работаешь
2 оставь везде промисы, у тебя мешанина получилась промисов и асинк/авейт

2022-11-20 08:23 UTC, greybutton commented on lib/tasks/js_routes.rake
> +    # debugger
коммент удалить

2022-11-20 14:40 UTC, igor-arkhipov commented on app/javascript/utils/fetchHelper.js
> +  async put(url, json) {
ок, поправлю − это eslint насоветовал дичи

2022-11-20 14:47 UTC, igor-arkhipov commented on app/javascript/components/EditPopup/EditPopup.js
> +import useStyles from './useStyles';
проверил/поправил везде

2022-11-21 02:08 UTC, igor-arkhipov commented on app/javascript/components/AddPopup/AddPopup.js
> +        console.log(`Creation Failed! Error: ${error.message}`);
Ок, пускай тогда алерты будут. В реальных проектах конечно лучше нормальным модальным окном.

2022-11-21 02:09 UTC, igor-arkhipov commented on app/controllers/api/v1/tasks_controller.rb
> +      order(id: :desc).
поправил

2022-11-21 06:54 UTC, greybutton approved these changes

2022-11-21 10:38 UTC, merged