added users and task models, fix tests
igor-arkhipov/TaskManager pull request #4
Opened 2021-11-21 11:37 UTC by igor-arkhipov

2021-11-21 19:35 UTC, greybutton requested changes

2021-11-21 19:35 UTC, greybutton commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
почему гем раскомментил?

2021-11-21 19:35 UTC, greybutton commented on test/models/task_test.rb
> +  # end
не дописан тест

2021-11-22 11:50 UTC, igor-arkhipov commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
ранее не был установлен, потребовался для rubocop https://cln.sh/z5ZoQ6

2021-11-22 12:06 UTC, igor-arkhipov commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
возможно ещё пары гемов не хвататает, тк описание предыдущего урока можно немного по разному толковать https://cln.sh/gw9SMz

2021-11-22 12:09 UTC, igor-arkhipov commented on test/models/task_test.rb
> +  # end
дописал

2021-11-22 15:46 UTC, greybutton commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
все целиком, давай здесь тогда добавим

2021-11-22 15:58 UTC, greybutton requested changes
добавь плис гемы недостающие с прошлого урока. сорян, что так вышло, не заметили)

2021-11-22 16:20 UTC, igor-arkhipov commented on Gemfile
> +gem 'bcrypt', '~> 3.1.7'
done!

2021-11-22 18:08 UTC, greybutton approved these changes

2021-11-22 18:57 UTC, merged